### ISSUE TITLE
LPIL第一届开发者大会

### ISSUE THREAD

**Issue by Guanrenfu** [Guanrenfu/LPIL#10]
`然而估计LPIL这个名称是最后一次使用了……`

各位好，这里是@Guanrenfu ：现任项目负责人。
本次大会的主要讨论内容就是以下三条：

>1、LPIL需要一个新名称，大家有何想法？
>2、是否应该采用@Arthur2e5 的#6。
>3、我想转让本项目，候选人为@Arthur2e5 和@veners1995 

欢迎诸位开发者以及其他关注者参与讨论。

**Comment by fybmain** [comment]
然而我什么也不清楚……

**Comment by fybmain** [comment]
名字就叫SSSSSS（Simple and Stupid Shell Script when Seeking for Software）……（笑眼）

**Comment by Guanrenfu** [comment]
@fybmain 哇您居然去注册了个帐号……（吐舌）。另外这个SSSSSS比我的SSS（System and Software Security）厉害多了耶！

**Comment by veners1995** [comment]
目前的名字确实容易引起误解，尽量和config搭上边吧

**Comment by Guanrenfu** [comment]
@veners1995 所以直接改名吧，有什么好的建议吗？`基地车`什么的好像实在有点……

**Comment by veners1995** [comment]
不太擅长起名字。。。。。。

**Comment by Guanrenfu** [comment]
@veners1995 好吧……

**Comment by Guanrenfu** [comment]
**给自己的项目转让找一个~~好丽友~~好理由**

>1、现在代码已经完全看不懂了……
>2、比我高明的人与代码很多，我不适合当本项目的负责人
>（如#3 #6 #1 等等，然而我根本看都看不懂……）

**最重要的一点，这样的话我就可以安心的~~水贴~~学习C和LaTeX了**（手动滑稽）

**Comment by Guanrenfu** [comment]
@Arthur2e5 @veners1995 @fybmain
