### ISSUE TITLE
关于在询问是否使用本脚本进行配置的步骤

### ISSUE THREAD

**Issue by veners1995** [Guanrenfu/LPIL#2]
如果用户选择1(继续使用)时，如果当前目录已存在continue.sh时，新的内容将会追加在文件末尾，如果continue.sh中在该脚本运行前存在其他内容，将会引起问题

**Comment by Guanrenfu** [comment]
好像有道理，那么就mv continue.sh continue.sh.backup 2> /dev/null怎样？

**Comment by veners1995** [comment]
mv -f continue.sh continue.sh.backup 2> /dev/null

**Comment by Guanrenfu** [comment]
好的，另外您的Shell在网页浏览器那里好像有语法错误：Vim在fi 和；；那两个终止的位置高亮红白了。

**Comment by veners1995** [comment]
谢谢提醒，我去看下

**Comment by Guanrenfu** [comment]
对了，经过查看问题不在那儿，删除那部分代码后还是会报错。

**Comment by Arthur2e5** [comment]
顺便也合并一下我的 sudo -H -u 吧。

**Comment by Arthur2e5** [comment]
另外看报错的 expect 状态还会不知道错在哪里吗……

**Comment by zx1986** [comment]
這些腳本基本的執行環境需要是  Ubuntu liked 的吧？

**Comment by Arthur2e5** [comment]
@zx1986 设计上默认认为存在的环境应该是基础 ArchLinux / Kali 安装。

**Comment by Guanrenfu** [comment]
@zx1986 当前只有KaliLinux（基于Debian7）和ArchLinux的版本，我们打算过些时候就开始开发Debian和Ubuntu适用的版本。

**Comment by Arthur2e5** [comment]
@Guanrenfu 如果你听得懂的话，建议合并 Debian 和 Ubuntu（甚至还有和 Kali）的大部分，需要分支的时候 if case 之类出去。

操作系统的探测可以借由
```Bash
. /etc/lsb-release
echo $DISTRIB_ID
# 或者用 systemd 统一的 os-release：
. /etc/os-release
echo $NAME
```
实现。具体你怎么弄那个变量而不是 echo 你应当知道。

**Comment by Guanrenfu** [comment]
@Arthur2e5 了解，但是Kali应该独立（由于单用户问题）。其他的凡是基于Debian的就可以多数通用了。
