### ISSUE TITLE
今天发现选项如果改一下的话会更加直观一些

### ISSUE THREAD

**Issue by Guanrenfu** [Guanrenfu/LPIL#5]
![screenshot from 2015-06-16 13-53-05](https://cloud.githubusercontent.com/assets/12596167/8177097/c6a12062-1433-11e5-9e72-a9434e267764.png)

今天发现SETookit的选项挺直观的，大概可以参考下。
@veners1995 有时间没有？表示最近实在略忙……如果像这样的话就没必要解释那么多还不容易出错了。

**Comment by Guanrenfu** [comment]
@veners1995 实在抱歉，刚刚看了下您的更新，发现我好像由于更改的过于频繁导致无意中覆盖了您的更新……在此向您抱歉，不好意思还请您帮忙修改下，今后我一定注意。

**Comment by veners1995** [comment]
建议接收@Arthur2e5的update

**Comment by Arthur2e5** [comment]
@veners1995 :smiley_cat: 的确 `select` 最方便易懂……不过我应该在 PS3 说明是选择一个序号，有空改一下好了。。

**Comment by Guanrenfu** [comment]
@Arthur2e5 你好无聊的～
@veners1995 好吧我去考虑下

**Comment by Guanrenfu** [comment]
@veners1995 
刚刚研究了下@Arthur2e5 的脚本，基本我是这么想的：
1、根据目前我的水平，只是看懂了20%的基础代码……
2、鉴于这个问题，如果我接受了您的更新，那么我将会特别尴尬：因为这是我的项目然而我却不能进行任何维护。

**Comment by Wiseluster** [comment]
Um, why not come n help us dev mosaic and maple? itll be fun.
Ive sent ya an invitation.

**Comment by Wiseluster** [comment]
The stagnancy of my projects really bothers me.

**Comment by Wiseluster** [comment]
@Guanrenfu

**Comment by Wiseluster** [comment]
Im right, ur project only interests chinese programmers.

**Comment by Guanrenfu** [comment]
@Wiseluster 说中文会死哦？？

**Comment by Arthur2e5** [comment]
@Guanrenfu 说实话，在英文界面的网站更多人想的应该是“卧槽，说英文会死吗”……

**Comment by Guanrenfu** [comment]
@Arthur2e5 But we're all chinese, right?
