### ISSUE TITLE
再次进行修改后发现无法正常安装桌面环境，问bug在哪儿？

### ISSUE THREAD

**Issue by Guanrenfu** [Guanrenfu/LPIL#7]
本次修改：
1、更改了一些换行，使整体看起来更加美观
2、使用“cat >file << EOF”这种形式代替部分“echo "*" >> /*/*”。

但是执行后发现无法正常将安装桌面环境的命令写入continue.sh，其他均正常
@veners1995 

以下是完整代码：https://github.com/Guanrenfu/LPIL/blob/master/ALS/NewTestVersion

**Comment by veners1995** [comment]
I tested the changes, and it works well on my machine. I think you should provide more details of this problem.

**Comment by Guanrenfu** [comment]
@veners1995 Well, Let me try it again.

**Comment by Guanrenfu** [comment]
@veners1995 
表示再次运行之后和上次一样，就是continue.sh里面没有正常的写入安装桌面环境的命令。话说你那边没问题？如果这样的话可能是我的Arch已经配置好了的原因（应该不受影响吧？）。如果没问题的话那么就直接让这个新版本的脚本代替旧版本的如何？
